[project]
name = "mcp-crash-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-groq>=1.1.1",
    "mcp-use>=1.5.0",
    "mcp[cli]>=1.24.0",
]
